"""
Security Finding Data Class for Tiny C Static Security Analyzer.

Represents a single static analysis security finding containing rule metadata,
source location, code snippet context, severity rating, and remediation advice.
"""

from dataclasses import dataclass, field
from typing import Any, Dict, Optional
from security.severity import Severity


@dataclass
class SecurityFinding:
    """Represents a vulnerability finding generated by AST security rules."""

    rule_id: str
    vulnerability_name: str
    description: str
    severity: Severity
    line: int = 0
    column: int = 0
    code_snippet: str = ""
    recommendation: str = ""
    attributes: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        """Serializes finding into dictionary format."""
        return {
            "rule_id": self.rule_id,
            "vulnerability_name": self.vulnerability_name,
            "description": self.description,
            "severity": str(self.severity),
            "line": self.line,
            "column": self.column,
            "code_snippet": self.code_snippet,
            "recommendation": self.recommendation,
        }

    def __str__(self) -> str:
        pos = f"Line {self.line}" if self.line > 0 else "Global"
        if self.column > 0:
            pos += f", Column {self.column}"
        return (
            f"[{self.rule_id}] [{self.severity.value}] {self.vulnerability_name} at {pos}\n"
            f"  Description: {self.description}\n"
            f"  Snippet: {self.code_snippet}\n"
            f"  Recommendation: {self.recommendation}"
        )
