"""
LALR(1) Parser Implementation for C/C++ Subset Compiler using PLY Yacc.

Parses token stream generated by TinyCLexer and constructs
a clean, strongly-typed Abstract Syntax Tree (ProgramNode).
"""

from typing import List, Optional, Any
import ply.yacc as yacc

from compiler.config import KEYWORDS, SECURITY_FUNCTIONS
from compiler.tokens import tokens
from compiler.lexer import TinyCLexer
from compiler.ast_nodes import (
    ASTNode,
    ProgramNode,
    BlockNode,
    VariableDeclarationNode,
    ConstantDeclarationNode,
    AssignmentNode,
    IdentifierNode,
    LiteralNode,
    BinaryExpressionNode,
    UnaryExpressionNode,
    IfStatementNode,
    WhileStatementNode,
    ForStatementNode,
    BreakNode,
    ContinueNode,
    ReturnNode,
    PrintNode,
    FunctionCallNode,
    ExpressionStatementNode,
    EmptyStatementNode,
    ErrorNode,
)
from compiler.ast_builder import ASTBuilder


class TinyCParser:
    """LALR(1) Parser constructing AST from C/C++ subset tokens."""

    tokens = tokens

    # Operator Precedence and Associativity Table
    precedence = (
        ("right", "ASSIGN", "PLUS_ASSIGN", "MINUS_ASSIGN", "TIMES_ASSIGN", "DIV_ASSIGN"),
        ("left", "OR"),
        ("left", "AND"),
        ("left", "EQ", "NE"),
        ("left", "LT", "LE", "GT", "GE"),
        ("left", "LSHIFT", "RSHIFT"),
        ("left", "PLUS", "MINUS"),
        ("left", "TIMES", "DIVIDE", "MODULO"),
        ("right", "NOT", "INC", "DEC"),
    )

    def __init__(self) -> None:
        self.lexer_instance = TinyCLexer()
        self.parser = yacc.yacc(module=self, write_tables=False, debug=False)

    # --- GRAMMAR PRODUCTIONS ---

    def p_program(self, p: yacc.YaccProduction) -> None:
        """program : statement_list
                   | main_function"""
        if isinstance(p[1], list):
            p[0] = ASTBuilder.build_program(p[1])
        elif isinstance(p[1], BlockNode):
            p[0] = ASTBuilder.build_program(p[1].statements)
        else:
            p[0] = ASTBuilder.build_program([p[1]])

    def p_main_function(self, p: yacc.YaccProduction) -> None:
        """main_function : INT MAIN LPAREN RPAREN block_statement
                         | INT MAIN LPAREN VOID RPAREN block_statement"""
        p[0] = p[len(p) - 1]

    def p_statement_list(self, p: yacc.YaccProduction) -> None:
        """statement_list : statement
                         | statement_list statement"""
        if len(p) == 2:
            p[0] = [p[1]] if p[1] is not None else []
        else:
            p[0] = p[1]
            if p[2] is not None:
                p[0].append(p[2])

    def p_type(self, p: yacc.YaccProduction) -> None:
        """type : INT
                | FLOAT
                | CHAR
                | STRING
                | BOOL
                | VOID"""
        p[0] = p[1]

    def p_statement(self, p: yacc.YaccProduction) -> None:
        """statement : var_declaration
                     | const_declaration
                     | assignment_statement
                     | if_statement
                     | while_statement
                     | for_statement
                     | return_statement
                     | break_statement
                     | continue_statement
                     | print_statement
                     | cout_statement
                     | cin_statement
                     | expression_statement
                     | block_statement
                     | main_function
                     | empty_statement"""
        p[0] = p[1]

    def p_empty_statement(self, p: yacc.YaccProduction) -> None:
        """empty_statement : SEMI"""
        p[0] = EmptyStatementNode(line=p.lineno(1), column=1)

    def p_var_declaration(self, p: yacc.YaccProduction) -> None:
        """var_declaration : type ID SEMI
                           | type ID ASSIGN expression SEMI
                           | type ID LBRACK INT_LITERAL RBRACK SEMI"""
        var_type = p[1]
        var_name = p[2]
        line = p.lineno(2)
        if len(p) == 4:
            p[0] = VariableDeclarationNode(var_type=var_type, var_name=var_name, line=line)
        elif len(p) == 6 and p[3] == "=":
            p[0] = VariableDeclarationNode(
                var_type=var_type, var_name=var_name, initializer=p[4], line=line
            )
        elif len(p) == 7:
            p[0] = VariableDeclarationNode(
                var_type=var_type, var_name=var_name, array_size=p[4], line=line
            )

    def p_const_declaration(self, p: yacc.YaccProduction) -> None:
        """const_declaration : CONST type ID ASSIGN expression SEMI"""
        p[0] = ConstantDeclarationNode(
            const_type=p[2], const_name=p[3], initializer=p[5], line=p.lineno(3)
        )

    def p_assignment_statement(self, p: yacc.YaccProduction) -> None:
        """assignment_statement : expression ASSIGN expression SEMI
                             | expression PLUS_ASSIGN expression SEMI
                             | expression MINUS_ASSIGN expression SEMI
                             | expression TIMES_ASSIGN expression SEMI
                             | expression DIV_ASSIGN expression SEMI"""
        p[0] = AssignmentNode(target=p[1], operator=p[2], value=p[3], line=p.lineno(2))

    def p_expression_statement(self, p: yacc.YaccProduction) -> None:
        """expression_statement : expression SEMI"""
        line = p[1].line if (hasattr(p[1], "line") and getattr(p[1], "line", 0) > 0) else p.lineno(1)
        p[0] = ExpressionStatementNode(expression=p[1], line=line)

    def p_if_statement(self, p: yacc.YaccProduction) -> None:
        """if_statement : IF LPAREN expression RPAREN statement
                        | IF LPAREN expression RPAREN statement ELSE statement"""
        line = p.lineno(1)
        if len(p) == 6:
            p[0] = IfStatementNode(condition=p[3], then_branch=p[5], line=line)
        else:
            p[0] = IfStatementNode(condition=p[3], then_branch=p[5], else_branch=p[7], line=line)

    def p_while_statement(self, p: yacc.YaccProduction) -> None:
        """while_statement : WHILE LPAREN expression RPAREN statement"""
        p[0] = WhileStatementNode(condition=p[3], body=p[5], line=p.lineno(1))

    def p_for_statement(self, p: yacc.YaccProduction) -> None:
        """for_statement : FOR LPAREN for_init SEMI for_cond SEMI for_update RPAREN statement"""
        p[0] = ForStatementNode(
            init=p[3], condition=p[5], update=p[7], body=p[9], line=p.lineno(1)
        )

    def p_for_init(self, p: yacc.YaccProduction) -> None:
        """for_init : var_declaration_no_semi
                    | assignment_no_semi
                    | empty"""
        p[0] = p[1]

    def p_var_declaration_no_semi(self, p: yacc.YaccProduction) -> None:
        """var_declaration_no_semi : type ID ASSIGN expression"""
        p[0] = VariableDeclarationNode(var_type=p[1], var_name=p[2], initializer=p[4], line=p.lineno(2))

    def p_assignment_no_semi(self, p: yacc.YaccProduction) -> None:
        """assignment_no_semi : ID ASSIGN expression"""
        target = IdentifierNode(name=p[1], line=p.lineno(1))
        p[0] = AssignmentNode(target=target, operator="=", value=p[3], line=p.lineno(1))

    def p_for_cond(self, p: yacc.YaccProduction) -> None:
        """for_cond : expression
                    | empty"""
        p[0] = p[1]

    def p_for_update(self, p: yacc.YaccProduction) -> None:
        """for_update : assignment_no_semi
                      | expression
                      | empty"""
        p[0] = p[1]

    def p_empty(self, p: yacc.YaccProduction) -> None:
        """empty :"""
        p[0] = None

    def p_return_statement(self, p: yacc.YaccProduction) -> None:
        """return_statement : RETURN expression SEMI
                             | RETURN SEMI"""
        line = p.lineno(1)
        if len(p) == 4:
            p[0] = ReturnNode(value=p[2], line=line)
        else:
            p[0] = ReturnNode(value=None, line=line)

    def p_break_statement(self, p: yacc.YaccProduction) -> None:
        """break_statement : BREAK SEMI"""
        p[0] = BreakNode(line=p.lineno(1))

    def p_continue_statement(self, p: yacc.YaccProduction) -> None:
        """continue_statement : CONTINUE SEMI"""
        p[0] = ContinueNode(line=p.lineno(1))

    def p_print_statement(self, p: yacc.YaccProduction) -> None:
        """print_statement : PRINT LPAREN expression RPAREN SEMI"""
        p[0] = PrintNode(expression=p[3], line=p.lineno(1))

    def p_cout_statement(self, p: yacc.YaccProduction) -> None:
        """cout_statement : COUT cout_stream_list SEMI"""
        p[0] = PrintNode(expression=p[2][0], line=p.lineno(1))

    def p_cout_stream_list(self, p: yacc.YaccProduction) -> None:
        """cout_stream_list : LSHIFT expression
                            | cout_stream_list LSHIFT expression"""
        if len(p) == 3:
            p[0] = [p[2]]
        else:
            p[0] = p[1]
            p[0].append(p[3])

    def p_cin_statement(self, p: yacc.YaccProduction) -> None:
        """cin_statement : CIN cin_stream_list SEMI"""
        p[0] = FunctionCallNode(func_name="scanf", arguments=p[2], line=p.lineno(1))

    def p_cin_stream_list(self, p: yacc.YaccProduction) -> None:
        """cin_stream_list : RSHIFT ID
                           | cin_stream_list RSHIFT ID"""
        id_node = IdentifierNode(name=p[len(p) - 1], line=p.lineno(1))
        if len(p) == 3:
            p[0] = [id_node]
        else:
            p[0] = p[1]
            p[0].append(id_node)

    def p_block_statement(self, p: yacc.YaccProduction) -> None:
        """block_statement : LBRACE statement_list RBRACE
                            | LBRACE RBRACE"""
        if len(p) == 4:
            p[0] = BlockNode(statements=p[2], line=p.lineno(1))
        else:
            p[0] = BlockNode(statements=[], line=p.lineno(1))

    # --- EXPRESSIONS ---

    def p_expression_binary(self, p: yacc.YaccProduction) -> None:
        """expression : expression PLUS expression
                      | expression MINUS expression
                      | expression TIMES expression
                      | expression DIVIDE expression
                      | expression MODULO expression
                      | expression EQ expression
                      | expression NE expression
                      | expression LT expression
                      | expression GT expression
                      | expression LE expression
                      | expression GE expression
                      | expression AND expression
                      | expression OR expression"""
        line = p[1].line if (hasattr(p[1], "line") and getattr(p[1], "line", 0) > 0) else p.lineno(2)
        p[0] = BinaryExpressionNode(left=p[1], operator=p[2], right=p[3], line=line)

    def p_expression_unary(self, p: yacc.YaccProduction) -> None:
        """expression : NOT expression
                      | MINUS expression %prec NOT
                      | INC expression
                      | DEC expression"""
        p[0] = UnaryExpressionNode(operator=p[1], operand=p[2], prefix=True, line=p.lineno(1))

    def p_expression_postfix(self, p: yacc.YaccProduction) -> None:
        """expression : expression INC
                      | expression DEC"""
        line = p[1].line if (hasattr(p[1], "line") and getattr(p[1], "line", 0) > 0) else p.lineno(2)
        p[0] = UnaryExpressionNode(operator=p[2], operand=p[1], prefix=False, line=line)

    def p_expression_group(self, p: yacc.YaccProduction) -> None:
        """expression : LPAREN expression RPAREN"""
        p[0] = p[2]

    def p_expression_primary(self, p: yacc.YaccProduction) -> None:
        """expression : primary_expression"""
        p[0] = p[1]

    def p_primary_expression(self, p: yacc.YaccProduction) -> None:
        """primary_expression : ID
                             | INT_LITERAL
                             | FLOAT_LITERAL
                             | CHAR_LITERAL
                             | STRING_LITERAL
                             | TRUE
                             | FALSE
                             | function_call"""
        if isinstance(p[1], ASTNode):
            p[0] = p[1]
        elif isinstance(p[1], bool):
            p[0] = LiteralNode(value=p[1], literal_type="bool", line=p.lineno(1))
        elif isinstance(p[1], int):
            p[0] = LiteralNode(value=p[1], literal_type="int", line=p.lineno(1))
        elif isinstance(p[1], float):
            p[0] = LiteralNode(value=p[1], literal_type="float", line=p.lineno(1))
        elif isinstance(p[1], str):
            if p.slice[1].type == "CHAR_LITERAL":
                p[0] = LiteralNode(value=p[1], literal_type="char", line=p.lineno(1))
            elif p.slice[1].type == "STRING_LITERAL":
                p[0] = LiteralNode(value=p[1], literal_type="string", line=p.lineno(1))
            else:
                p[0] = IdentifierNode(name=p[1], line=p.lineno(1))

    def p_function_call(self, p: yacc.YaccProduction) -> None:
        """function_call : func_name LPAREN argument_list RPAREN
                         | func_name LPAREN RPAREN"""
        func_name = p[1]
        line = p.lineno(1)
        if len(p) == 5:
            p[0] = FunctionCallNode(func_name=func_name, arguments=p[3], line=line)
        else:
            p[0] = FunctionCallNode(func_name=func_name, arguments=[], line=line)

    def p_func_name(self, p: yacc.YaccProduction) -> None:
        """func_name : ID
                     | PRINTF
                     | SCANF
                     | SEC_DB_QUERY
                     | SEC_SYSTEM
                     | SEC_GETS
                     | SEC_STRCPY
                     | SEC_SPRINTF
                     | SEC_STRCAT
                     | SEC_RAND
                     | SEC_SECURE_RAND
                     | SEC_OPEN
                     | SEC_READ
                     | SEC_WRITE
                     | SEC_CLOSE"""
        p[0] = p[1]
        p.set_lineno(0, p.lineno(1))

    def p_argument_list(self, p: yacc.YaccProduction) -> None:
        """argument_list : expression
                         | argument_list COMMA expression"""
        if len(p) == 2:
            p[0] = [p[1]]
        else:
            p[0] = p[1]
            p[0].append(p[3])

    def p_error(self, p: yacc.YaccProduction) -> None:
        if p:
            err_msg = f"Syntax error at token '{p.value}' ({p.type})"
            line = p.lineno
        else:
            err_msg = "Syntax error at end of file"
            line = 1
        return ErrorNode(error_message=err_msg, line=line)

    def parse(self, source_code: str) -> ProgramNode:
        """Parses C/C++ subset source code into an AST ProgramNode root."""
        self.lexer_instance.lexer.lineno = 1
        return self.parser.parse(source_code, lexer=self.lexer_instance.lexer)
